import type {Metadata} from 'next'
import '@/styles/base/_global.scss'
import {ApolloProvider} from "../ApolloProvider";
import {RootLayoutClient} from "./RootLayoutClient";

export const metadata: Metadata = {
    title: 'Unity Gram',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {

    return (
        <html lang="en">
        <body>
            <ApolloProvider>
                <RootLayoutClient>
                    {children}
                </RootLayoutClient>
            </ApolloProvider>
        </body>
        </html>
    )
}
